spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: off
    properties:
      hibernate:
        format_sql: true
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          google:
            clientId: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID}
            clientSecret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET}
  youtubeApiKey: ${YOUTUBE_API_KEY}
<<<<<<< HEAD
spring.security.user:
  name: 사용자이름
  password: 비밀번호
  roles: USER
  server:
    servlet:
      session:
        timeout=1800:
logging:
  level:
    root: debug
=======
  KdmbApiKey: ${KDMB_API_KEY}
  KobisApiKEY: ${KOBIS_API_KEY}
>>>>>>> a8a0389c2ebfab9d514e616169e240966ee9b6a8
